version: '3.8'
services:
    mongodb:
        container_name: mongodb
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=password
            - MONGO_INITDB_ROOT_PASSWORD=username
        volumes:
            - ./data:/data/db
        command: mongod --port 27017
        ports:
            - "27017:27017"
        networks:
            - default    

    node-api:
       container_name: telunjuk-api
       build:
           context: ./pointSystem
           dockerfile: Dockerfile
       depends_on:
           - mongodb
       volumes:
          # - /app/node_modules
          - ./pointSystem:/app
       ports:
           - "3000:3000"
       networks:
            - default

networks:
    default:
        external: true
        name: telunjuk
